"""
Phase 5 gate — T22 contract (Pydantic + tsc cross-check), T23 SSE,
T24 error surface, T25 validation table. Runs the real app over TestClient
against the live PostgreSQL; startup fixture seeding is idempotent.
"""
from __future__ import annotations

import asyncio
import json
import pathlib
import subprocess

import pytest
from fastapi.testclient import TestClient

from app.api import schemas
from app.main import app

FRONTEND = pathlib.Path("/home/claude/work/qsentinel/qsentinel-main")


@pytest.fixture(scope="module")
def client():
    with TestClient(app) as c:
        yield c


# ---------------------------------------------------------------- T22: contract
def test_t22_pydantic_validates_all_fixture_reads(client):
    from app.fixtures import FIXTURES
    hist = client.get("/api/history")
    assert hist.status_code == 200
    schemas.HistoryResponse.model_validate(hist.json())

    sysr = client.get("/api/system")
    assert sysr.status_code == 200
    schemas.SystemResponse.model_validate(sysr.json())

    b = client.get("/api/analysis/binomial",
                   params={"n": 128, "p_honest": 0.02, "p_cheat": 0.34})
    assert b.status_code == 200
    schemas.BinomialResponse.model_validate(b.json())

    for sid, *_ in FIXTURES:
        r = client.get(f"/api/runs/{sid}/result")
        assert r.status_code == 200, (sid, r.text)
        schemas.ResultResponse.model_validate(r.json())
        lg = client.get(f"/api/runs/{sid}/logs")
        assert lg.status_code == 200
        for row in lg.json():
            schemas.LogRow.model_validate(row)


def test_t22_tsc_crosscheck_real_json_against_types_ts(client):
    """Real backend JSON, embedded as fresh literals, must `satisfies` the
    frontend's own types. Excess keys or wrong unions fail compilation."""
    result = client.get("/api/runs/honest7/result").json()
    forged = client.get("/api/runs/e4f5a1/result").json()
    system = client.get("/api/system").json()
    history = client.get("/api/history").json()
    events = []
    with client.stream("GET", "/api/runs/j8k3w9/events") as s:
        buf = ""
        for chunk in s.iter_text():
            buf += chunk
        for frame in buf.split("\n\n"):
            for line in frame.split("\n"):
                if line.startswith("data:"):
                    events.append(json.loads(line[5:].strip()))

    ts = f"""// generated by test_phase5_api — do not commit
import type {{ ResultResponse, RunEvent, HistoryResponse, SystemResponse }} from "./src/api/types";
const honest = {json.dumps(result)} satisfies ResultResponse;
const forged = {json.dumps(forged)} satisfies ResultResponse;
const sys = {json.dumps(system)} satisfies SystemResponse;
const hist = {json.dumps(history)} satisfies HistoryResponse;
const evs = {json.dumps(events)} satisfies RunEvent[];
export {{ honest, forged, sys, hist, evs }};
"""
    out = FRONTEND / "wire-check.generated.ts"
    cfg = FRONTEND / "tsconfig.wirecheck.json"
    out.write_text(ts)
    cfg.write_text(json.dumps({
        "extends": "./tsconfig.app.json",
        "include": ["wire-check.generated.ts", "src/api/types.ts"],
        "compilerOptions": {"noEmit": True, "strict": True},
    }))
    try:
        proc = subprocess.run(["npx", "tsc", "-p", str(cfg)],
                              cwd=FRONTEND, capture_output=True, text=True,
                              timeout=300)
        assert proc.returncode == 0, proc.stdout + proc.stderr
    finally:
        out.unlink(missing_ok=True)
        cfg.unlink(missing_ok=True)


# ---------------------------------------------------------------- T23: SSE
def test_t23_sse_order_headers_done(client):
    r = client.get("/api/runs/honest7/events")
    assert r.headers["content-type"].startswith("text/event-stream")
    assert r.headers["cache-control"] == "no-cache"
    assert r.headers["x-accel-buffering"] == "no"
    frames = [json.loads(l[5:].strip()) for l in r.text.split("\n")
              if l.startswith("data:")]
    assert frames[0]["kind"] == "session"
    assert frames[-1]["kind"] == "done"
    ts = [f["tMs"] for f in frames]
    assert ts == sorted(ts), "tMs must be non-decreasing in stream order"
    kinds = [f["kind"] for f in frames]
    assert kinds.count("verify-bag") == 126  # 63 bags x 2 verifiers
    # matches the DB byte-for-byte, in order
    from app.db import db as kit
    from app.db import repository as repo
    with kit.transaction() as s:
        assert frames == repo.events_of(s, "honest7")


def test_t23_disconnect_stops_stream():
    """The generator must stop (not keep yielding) once the client is gone."""
    from app.api.routes import events

    class GoneRequest:
        async def is_disconnected(self):
            return True

    resp = asyncio.run(events("honest7", GoneRequest()))

    async def drain():
        return [chunk async for chunk in resp.body_iterator]

    chunks = asyncio.run(drain())
    assert len(chunks) == 0, "stream kept yielding after disconnect"


def test_t23_streaming_run_not_found(client):
    r = client.get("/api/runs/nope1234/events")
    assert r.status_code == 404 and r.json()["code"] == "RUN_NOT_FOUND"


# ---------------------------------------------------------------- T24: errors
def test_t24_error_surface(client, monkeypatch):
    r = client.get("/api/runs/zzzzzz99/result")
    assert r.status_code == 404
    body = r.json()
    assert body["code"] == "RUN_NOT_FOUND" and "zzzzzz99" in body["message"]

    r = client.post("/api/runs", json={"attack": "replay", "message": "x"})
    assert r.status_code == 400 and r.json()["code"] == "INVALID_PARAMS"

    r = client.post("/api/runs", json={"attack": "warp-drive", "message": "x"})
    assert r.status_code == 400 and r.json()["code"] == "INVALID_PARAMS"

    r = client.post("/api/runs/zzzzzz99/rerun", json={})
    assert r.status_code == 404 and r.json()["code"] == "RUN_NOT_FOUND"

    # forced engine crash -> 500 BACKEND_ERROR + FAILED row + 412 on later reads
    from app.api import routes as R

    def boom(*a, **k):
        raise RuntimeError("synthetic engine crash")

    monkeypatch.setattr(R.pipeline, "run", boom)
    r = client.post("/api/runs", json={"attack": "no-attack", "message": "CRASH ME"})
    assert r.status_code == 500
    body = r.json()
    assert body["code"] == "BACKEND_ERROR" and "detail" in body
    monkeypatch.undo()

    from app.db import db as kit
    from app.db.models import Run
    from sqlalchemy import select
    with kit.transaction() as s:
        row = s.execute(select(Run).where(Run.message == "CRASH ME")
                        .order_by(Run.created_at.desc())).scalars().first()
        assert row is not None and row.status == "FAILED"
        failed_sid = row.session_id
    r = client.get(f"/api/runs/{failed_sid}/result")
    assert r.status_code == 412 and r.json()["code"] == "INVALID_STATE"
    r = client.get(f"/api/runs/{failed_sid}/events")
    assert r.status_code == 412


# ---------------------------------------------------------------- T25: validation
GOOD = {"attack": "no-attack", "message": "HELLO"}

CASES = [
    # (body, ok)
    (GOOD, True),
    ({"attack": "no-attack", "message": ""}, False),
    ({"attack": "no-attack", "message": " " * 5}, False),
    ({"attack": "no-attack", "message": "x" * 65}, False),
    ({"attack": "no-attack", "message": "x", "seed": 2 ** 53}, False),
    ({"attack": "no-attack", "message": "x", "seed": 7}, True),
    ({"attack": "no-attack", "message": "x", "target_link": "bob"}, False),
    ({"attack": "forgery", "message": "x"}, True),
    ({"attack": "forgery", "message": "x", "target_link": "bob"}, False),
    ({"attack": "replay", "message": "x"}, False),
    ({"attack": "replay", "message": "x", "replay_type": "used"}, True),
    ({"attack": "replay", "message": "x", "replay_type": "unknown"}, True),
    ({"attack": "replay", "message": "x", "replay_type": "twice"}, False),
    ({"attack": "tampering", "message": "x"}, False),
    ({"attack": "tampering", "subtype": "fixed-basis", "message": "x",
      "target_link": "bob"}, False),                       # missing fixed_basis
    ({"attack": "tampering", "subtype": "fixed-basis", "message": "x",
      "target_link": "bob", "fixed_basis": "Z"}, True),
    ({"attack": "tampering", "subtype": "fixed-basis", "message": "x",
      "fixed_basis": "Z"}, False),                         # missing target_link
    ({"attack": "tampering", "subtype": "random-basis", "message": "x",
      "target_link": "charlie"}, True),
    ({"attack": "tampering", "subtype": "partial", "message": "x",
      "target_link": "both"}, True),                       # default 25
    ({"attack": "tampering", "subtype": "partial", "message": "x",
      "target_link": "both", "intensity_pct": 5}, True),
    ({"attack": "tampering", "subtype": "partial", "message": "x",
      "target_link": "both", "intensity_pct": 7}, False),  # not a step of 5
    ({"attack": "tampering", "subtype": "partial", "message": "x",
      "target_link": "both", "intensity_pct": 105}, False),
    ({"attack": "tampering", "subtype": "message-substitution", "message": "PAY 10",
      "target_link": "both", "tampered_message": "PAY 10"}, False),  # identical
    ({"attack": "tampering", "subtype": "message-substitution", "message": "PAY 10",
      "target_link": "both", "tampered_message": "PAY 99"}, True),
    ({"attack": "tampering", "subtype": "message-substitution", "message": "PAY 10",
      "target_link": "both"}, False),                      # missing tampered
    ({"attack": "tampering", "subtype": "correction-bit", "message": "x",
      "target_link": "bob"}, True),
    ({"attack": "tampering", "subtype": "correction-bit", "message": "x",
      "target_link": "bob", "intensity_pct": 25}, False),  # inapplicable field
    ({"attack": "impersonation", "message": "x", "replay_type": "used"}, False),
]


@pytest.mark.parametrize("body,ok", CASES)
def test_t25_validation_table(client, body, ok):
    if ok:
        body = dict(body, seed=body.get("seed", 12345))  # keep the run deterministic
    r = client.post("/api/runs", json=body)
    if ok:
        assert r.status_code == 200, (body, r.text)
        out = r.json()
        assert set(out) == {"session_id", "seed", "config"}
        assert len(out["session_id"]) == 8
    else:
        assert r.status_code == 400, (body, r.status_code, r.text)
        assert r.json()["code"] == "INVALID_PARAMS"


def test_t25_binomial_bounds(client):
    assert client.get("/api/analysis/binomial",
                      params={"n": 513, "p_honest": 0.02, "p_cheat": 0.34}
                      ).status_code == 400
    assert client.get("/api/analysis/binomial",
                      params={"n": 0, "p_honest": 0.02, "p_cheat": 0.34}
                      ).status_code == 400
    assert client.get("/api/analysis/binomial",
                      params={"n": 512, "p_honest": 0.02, "p_cheat": 1.5}
                      ).status_code == 400
