/**
 * New Simulation (`/simulate/new`) — design report, section 4.2.
 *
 * The setup is deliberately small: pick a scenario, set noise / qubits per
 * slot / verifier count, and go. Everything quantum-mechanical (bases, Bell
 * pairs, nonces, the MAC key, the seed) is generated by the backend and is
 * never asked for here.
 *
 * The threshold is backend-derived. It is shown in the preview and can be
 * overridden in Advanced Configuration, but the frontend never computes it.
 */

import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../api";
import {
  ATTACK_OPTIONS,
  type AttackTypeId,
  type SimulationParameters,
} from "../api/types";
import { useApi } from "../lib/useApi";
import { pct, rate } from "../lib/formatting";
import {
  Banner,
  CountStepper,
  DataCard,
  EmptyState,
  Icon,
  Panel,
  ParamSlider,
  SectionHead,
} from "../components/ui/atoms";
import { ErrorBanner } from "../components/ui/ErrorBanner";

/** Fallback ranges, used only until the backend's preview declares its own. */
const FALLBACK = {
  noise: { min: 0, max: 0.12, default: 0.02, step: 0.001 },
  qubitsPerSlot: { min: 100, max: 2000, default: 1000, step: 50 },
  verifierCount: { min: 1, max: 4, default: 2 },
};

const asPercent = (v: number) => `${(v * 100).toFixed(1)}%`;

export function NewSimulationPage() {
  const navigate = useNavigate();

  const [attack, setAttack] = useState<AttackTypeId>("honest");
  const [noise, setNoise] = useState(FALLBACK.noise.default);
  const [qubitsPerSlot, setQubits] = useState(FALLBACK.qubitsPerSlot.default);
  const [verifierCount, setVerifierCount] = useState(
    FALLBACK.verifierCount.default,
  );
  const [attackFraction, setAttackFraction] = useState(0.1);
  const [advanced, setAdvanced] = useState(false);
  const [thresholdOverride, setThresholdOverride] = useState<number | null>(
    null,
  );
  const [running, setRunning] = useState(false);

  const option = useMemo(
    () => ATTACK_OPTIONS.find((a) => a.id === attack) ?? ATTACK_OPTIONS[0]!,
    [attack],
  );

  const params: SimulationParameters = useMemo(
    () => ({
      attackType: attack,
      noise,
      qubitsPerSlot,
      verifierCount,
      ...(option.hasIntensity ? { attackFraction } : {}),
      ...(thresholdOverride !== null ? { thresholdOverride } : {}),
    }),
    [
      attack,
      noise,
      qubitsPerSlot,
      verifierCount,
      option.hasIntensity,
      attackFraction,
      thresholdOverride,
    ],
  );

  /* the backend owns the valid ranges, so read them off the preview */
  const {
    data: preview,
    loading: previewLoading,
    error,
  } = useApi(() => api.preview(params), [params]);
  const supported = preview?.supported ?? FALLBACK;

  /* the backend owns the valid ranges, so adopt its declared defaults on the
     first preview and clamp anything it later tightens */
  const adopted = useRef(false);
  useEffect(() => {
    if (!preview) return;
    if (!adopted.current) {
      adopted.current = true;
      setNoise(preview.supported.noise.default);
      setQubits(preview.supported.qubitsPerSlot.default);
      setVerifierCount(preview.supported.verifierCount.default);
      return;
    }
    setNoise((v) => clampTo(v, preview.supported.noise));
    setQubits((v) => clampTo(v, preview.supported.qubitsPerSlot));
    setVerifierCount((v) => clampTo(v, preview.supported.verifierCount));
  }, [preview]);

  const verifierError =
    verifierCount < option.minVerifiers
      ? `At least ${option.minVerifiers} verifiers are required for this scenario.`
      : undefined;

  const canSubmit = !verifierError && !running;

  const launch = async () => {
    if (!canSubmit) return;
    setRunning(true);
    try {
      const run = await api.createRun(params);
      navigate(`/simulate/run/${run.runId}`);
    } catch {
      setRunning(false);
    }
  };

  return (
    <div className="mx-auto max-w-6xl px-6 py-14 md:px-10">
      <p className="micro text-accent-ink">Configure a run</p>
      <h1 className="mt-2 font-display text-[28px] leading-tight font-semibold text-on-bg">
        New simulation
      </h1>
      <p className="mt-3 max-w-2xl text-[15px] leading-relaxed text-n-600">
        Pick a scenario and set the channel conditions. The threshold, the
        measurement outcomes and the verdict all come from the backend.
      </p>

      <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]">
        {/* ------------------------- attack selection ------------------------- */}
        <div>
          <SectionHead step="A" title="Attack scenario">
            <span className="micro text-n-500">
              {ATTACK_OPTIONS.length} scenarios
            </span>
          </SectionHead>

          <fieldset>
            <legend className="sr-only">Attack scenario</legend>
            <div className="grid gap-2 sm:grid-cols-2">
              {ATTACK_OPTIONS.map((opt) => {
                const active = opt.id === attack;
                return (
                  <button
                    key={opt.id}
                    type="button"
                    onClick={() => setAttack(opt.id)}
                    aria-pressed={active}
                    className={`rounded-[var(--qs-r)] border p-3.5 text-left transition-colors ${
                      active
                        ? "border-primary bg-surface-2 ring-1 ring-primary"
                        : "border-outline bg-surface hover:border-outline-strong"
                    }`}
                  >
                    <span className="flex items-center gap-2">
                      <span
                        className={`grid size-5 shrink-0 place-items-center rounded-full border ${
                          active
                            ? "border-primary bg-primary text-on-primary"
                            : "border-outline-strong text-transparent"
                        }`}
                        aria-hidden
                      >
                        <Icon name="shield-check" size={12} />
                      </span>
                      <span
                        className={`flex min-w-0 items-center gap-1.5 ${
                          active ? "text-on-bg" : "text-n-600"
                        }`}
                      >
                        <Icon name={opt.icon} size={15} className="shrink-0" />
                        <span className="display text-[13px] font-semibold tracking-[0.02em] uppercase">
                          {opt.label}
                        </span>
                      </span>
                    </span>
                    <span className="mt-2 block text-[13px] leading-snug text-n-600">
                      {opt.description}
                    </span>
                    {opt.minVerifiers > 1 && (
                      <span className="micro mt-2 block text-accent-ink">
                        needs {opt.minVerifiers}+ verifiers
                      </span>
                    )}
                  </button>
                );
              })}
            </div>
          </fieldset>

          <div className="mt-6">
            <Banner tone="brand" title="What this run will show">
              <p>{option.description}</p>
            </Banner>
          </div>
        </div>

        {/* ------------------------- parameters ------------------------- */}
        <div>
          <SectionHead step="B" title="Channel configuration" />

          <Panel className="space-y-6 p-5">
            <ParamSlider
              label="Channel noise"
              value={noise}
              min={supported.noise.min}
              max={supported.noise.max}
              step={supported.noise.step}
              unit=""
              format={asPercent}
              onChange={setNoise}
              hint="Noise the quantum channel adds to every transmission."
            />

            <ParamSlider
              label="Qubits per slot"
              value={qubitsPerSlot}
              min={supported.qubitsPerSlot.min}
              max={supported.qubitsPerSlot.max}
              step={supported.qubitsPerSlot.step}
              onChange={setQubits}
              hint="How many states each time slot carries. Bases and values are generated server-side."
            />

            <CountStepper
              label="Verifier count"
              value={verifierCount}
              min={supported.verifierCount.min}
              max={supported.verifierCount.max}
              onChange={setVerifierCount}
              hint="Every verifier measures independently and reports its own verdict."
              error={verifierError}
            />

            {option.hasIntensity && (
              <ParamSlider
                label="Attack fraction"
                value={attackFraction}
                min={0.01}
                max={1}
                step={0.01}
                format={asPercent}
                onChange={setAttackFraction}
                hint="Fraction of qubits the stealth attack touches. The backend picks which ones; a small fraction can stay below the detection threshold."
              />
            )}
          </Panel>

          {/* ---------------------- advanced configuration ---------------------- */}
          <div className="mt-6">
            <button
              type="button"
              className="btn btn-ghost btn-sm"
              onClick={() => setAdvanced((v) => !v)}
              aria-expanded={advanced}
              aria-controls="advanced-config"
            >
              {advanced ? "Hide" : "Show"} advanced configuration
            </button>

            {advanced && (
              <div id="advanced-config">
                <Panel className="mt-3 space-y-4 p-5">
                  <div>
                    <p className="display text-[13px] font-medium tracking-[0.04em] text-on-surface uppercase">
                      Detection threshold
                    </p>
                    <p className="mt-1.5 text-[13px] leading-relaxed text-n-500">
                      Normally derived automatically by the backend from the
                      simulation configuration. Override it only if you need to
                      pin a specific value — the frontend never calculates it.
                    </p>
                    {preview && thresholdOverride === null && (
                      <p className="num mt-2 text-[13px] text-on-surface">
                        Backend-derived value for this configuration:{" "}
                        <span className="font-semibold">
                          {rate(preview.threshold)}
                        </span>
                      </p>
                    )}
                    <div className="mt-3 flex flex-wrap items-center gap-2">
                      <input
                        type="number"
                        min={0}
                        max={1}
                        step={0.005}
                        value={thresholdOverride ?? preview?.threshold ?? 0.1}
                        onChange={(e) =>
                          setThresholdOverride(Number(e.target.value))
                        }
                        aria-label="Detection threshold override"
                        className="num w-32 rounded-[var(--qs-r)] border border-outline-strong bg-surface px-3 py-2 text-[14px] text-on-surface"
                      />
                      {thresholdOverride !== null && (
                        <button
                          type="button"
                          className="btn btn-ghost btn-sm"
                          onClick={() => setThresholdOverride(null)}
                        >
                          Reset to derived
                        </button>
                      )}
                    </div>
                  </div>
                </Panel>
              </div>
            )}
          </div>

          {/* ---------------------- preview ---------------------- */}
          <div className="mt-6">
            <SectionHead step="C" title="Backend preview">
              <span className="micro text-n-500">
                GET /api/simulate/preview
              </span>
            </SectionHead>
            <Panel className="p-5">
              {previewLoading && <div className="skeleton h-24 w-full" />}
              {preview && (
                <div className="space-y-4">
                  {preview.predictedDetectionConfidence === null ? (
                    <EmptyState title="No prediction for this configuration">
                      {attack === "honest"
                        ? "An honest baseline has nothing to detect, so the backend returns no predicted confidence."
                        : "At this attack fraction the backend does not predict detection ahead of the run. Start it to see the measured outcome."}
                    </EmptyState>
                  ) : (
                    <DataCard
                      label="Predicted detection confidence"
                      value={preview.predictedDetectionConfidence.toFixed(2)}
                      tone="brand"
                      hint="A hint from the backend, not a guarantee. The run's measured result is what counts."
                    />
                  )}

                  <DataCard
                    label={
                      (params.thresholdOverride ?? preview.thresholdSource) ===
                      "override"
                        ? "Detection threshold (overridden)"
                        : "Detection threshold (backend-derived)"
                    }
                    value={rate(params.thresholdOverride ?? preview.threshold)}
                    hint="Derived by the backend from the qubit count, the noise and the simulation configuration."
                  />

                  <p className="num text-[12px] text-n-500">
                    {pct(noise)} noise · {qubitsPerSlot.toLocaleString()} qubits
                    per slot · {verifierCount} verifier
                    {verifierCount === 1 ? "" : "s"}
                    {option.hasIntensity
                      ? ` · ${asPercent(attackFraction)} attacked`
                      : ""}
                  </p>
                </div>
              )}
            </Panel>
          </div>

          {verifierError && (
            <div className="mt-4">
              <Banner tone="warn" title="Fix before running">
                <p>{verifierError}</p>
              </Banner>
            </div>
          )}

          <button
            type="button"
            className="btn btn-primary mt-6 w-full"
            disabled={!canSubmit}
            onClick={() => void launch()}
          >
            {running ? "Starting run…" : "Start simulation"}
          </button>
        </div>
      </div>

      <ErrorBanner error={error} />
    </div>
  );
}

const clamp = (v: number, min: number, max: number) =>
  Math.min(max, Math.max(min, v));
const clampTo = (v: number, r: { min: number; max: number }) =>
  clamp(v, r.min, r.max);
